apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: full-app
  namespace: openshift-gitops
  annotations:
    argocd-image-updater.argoproj.io/backend.image-name: docker.io/pratama84/note_api
    argocd-image-updater.argoproj.io/backend.update-strategy: latest
    argocd-image-updater.argoproj.io/backend.force-update: "true"
    argocd-image-updater.argoproj.io/frontend.image-name: docker.io/pratama84/note_ui
    argocd-image-updater.argoproj.io/frontend.update-strategy: latest
    argocd-image-updater.argoproj.io/frontend.force-update: "true"
spec:
  project: default
  source:
    repoURL: 'https://github.com/azma8/argocd-noteapp.git'
    targetRevision: main
    path: app
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: note-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true


